### ISSUE TITLE
Problem with localization of PDF reports. Need to change the language in the report output file.

### ISSUE THREAD

**Issue by lomovtsevivan** [eroshenkoam/allure-pdf#26]
Greetings. There is a need to change the language to Russian in the output file of the report. For now reports are generated in English. Is it possible to change the language? There is no information about this in the help section of the console tool.

**Comment by Sai7574** [comment]
Found [13] rest results ...
log4j:WARN No appenders could be found for logger (org.apache.fop.fonts.apps.AbstractFontReader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
        at io.github.eroshenkoam.allure.AllurePDFGenerator.addTestResultHeader(AllurePDFGenerator.java:145)
        at io.github.eroshenkoam.allure.AllurePDFGenerator.printTestResultDetails(AllurePDFGenerator.java:133)
        at io.github.eroshenkoam.allure.AllurePDFGenerator.generate(AllurePDFGenerator.java:107)
        at io.github.eroshenkoam.allure.MainCommand.run(MainCommand.java:53)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at io.github.eroshenkoam.allure.AllurePDF.main(AllurePDF.java:13)
![Screenshot (6)](https://github.com/eroshenkoam/allure-pdf/assets/113346566/a54990e7-abf7-405a-bcb4-f03df7809519)
can any one help on this not generating pdf report Thanks

**Comment by jayanthmuthu10** [comment]
Try like this..

C:\Users\54978\Playwright\allure-pdf-1.6.0\bin>allure-pdf "C:\Users\54978\Playwright\SGEF_V3_Jayanth\allure-results" -o report1.pdf
