### ISSUE TITLE
Below error iam getting when i entered command report is generating but no data how ?

### ISSUE THREAD

**Issue by Sai7574** [eroshenkoam/allure-pdf#28]
Found [13] rest results ...
log4j:WARN No appenders could be found for logger (org.apache.fop.fonts.apps.AbstractFontReader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
at io.github.eroshenkoam.allure.AllurePDFGenerator.addTestResultHeader(AllurePDFGenerator.java:145)
at io.github.eroshenkoam.allure.AllurePDFGenerator.printTestResultDetails(AllurePDFGenerator.java:133)
at io.github.eroshenkoam.allure.AllurePDFGenerator.generate(AllurePDFGenerator.java:107)
at io.github.eroshenkoam.allure.MainCommand.run(MainCommand.java:53)
at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
at picocli.CommandLine.execute(CommandLine.java:1904)
at io.github.eroshenkoam.allure.AllurePDF.main(AllurePDF.java:13)

**Comment by jayanthmuthu10** [comment]
Try like this..

C:\Users\54978\Playwright\allure-pdf-1.6.0\bin>allure-pdf "C:\Users\54978\Playwright\SGEF_V3_Jayanth\allure-results" -o report1.pdf

Also check in the bin folder. There might be a possibility that the report has been generated.

**Comment by Sai7574** [comment]
Since I'm not using a playwright, how can I address Thanks for the response

**Comment by jayanthmuthu10** [comment]
You can use any automation tool thats not an issue.
Let me explain the command clearly..
C:\Users\54978\Playwright\allure-pdf-1.6.0\bin>allure-pdf "C:\Users\54978\Playwright\SGEF_V3_Jayanth\allure-results" -o report1.pdf
1) C:\Users\54978\Playwright\allure-pdf-1.6.0\bin>allure-pdf  - This is the path where I have downloaded the zip file and extracted. The zip file is available in the releases. You should give the path where you have the 'bin' folder.
2)C:\Users\54978\Playwright\SGEF_V3_Jayanth\allure-results - This is the path where I have the 'allure-results' folder. You should give yours.
3)report1.pdf - This is the name of the pdf that is gonna be generated. It will be downloaded in 'bin' folder.

Hope this helps.

**Comment by Sai7574** [comment]
Yes it is generating but in pdf there is no data only empty pdf is generating are you also faced same issue if it reslove please guide me thanks

**Comment by jayanthmuthu10** [comment]
Clear the allure results folder. Run the test file. Generate now. I think it should work.

**Comment by Sai7574** [comment]
[report1.pdf](https://github.com/eroshenkoam/allure-pdf/files/13700277/report1.pdf)
Yes it is generating but screenshots are not available and it is printing j-son data, how to overcome that and need to print screenshots as well Plz refer above report

**Comment by Sai7574** [comment]
![image](https://github.com/eroshenkoam/allure-pdf/assets/113346566/493552c5-0210-49b2-adb6-be7c19200f6c)
 it is generating but in pdf there is no data only empty pdf is generating are you also faced same issue if it resolve please guide me thanks, Previous it was working fine but now again facing above error

**Comment by jayanthmuthu10** [comment]
allure-docx --detail-level compact "C:\Users\54978\Playwright\Testing\allure-results" "C:\Users\54978\Desktop\report1.docx"

Try this command or please remove '-o' from your command and try executing it.

**Comment by Sai7574** [comment]
![image](https://github.com/eroshenkoam/allure-pdf/assets/113346566/c2633153-e542-40c8-973a-6b97db648965)
I tried, but an error was received.Please refer to the screenshot that is attached.
I am also getting errors when I remove "-o" from the command. Do what is necessary, please.
